stages:
  - test

check-fmt+run-test:
  stage: test
  image: nixpkgs/nix-flakes:nixos-24.11
  script: 
    - nix develop --command cargo fmt --check
    - nix develop --command cargo test
  parallel:
    matrix:
      - NIXPKGS_CHANNEL:
        - nixos-24.11